//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp39
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.ACC_TRANSACTION = new HashSet<ACC_TRANSACTION>();
        }
    
        public int ACCOUNT_ID { get; set; }
        public Nullable<double> AVAIL_BALANCE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public Nullable<System.DateTime> LAST_ACTIVITY_DATE { get; set; }
        public System.DateTime OPEN_DATE { get; set; }
        public Nullable<double> PENDING_BALANCE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CUST_ID { get; set; }
        public int OPEN_BRANCH_ID { get; set; }
        public int OPEN_EMP_ID { get; set; }
        public string PRODUCT_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_TRANSACTION> ACC_TRANSACTION { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
