//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp39
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
            this.OFFICER = new HashSet<OFFICER>();
        }
    
        public int CUST_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string CUST_TYPE_CD { get; set; }
        public string FED_ID { get; set; }
        public string POSTAL_CODE { get; set; }
        public string STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        public virtual BUSINESS BUSINESS { get; set; }
        public virtual INDIVIDUAL INDIVIDUAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFFICER> OFFICER { get; set; }
    }
}
