//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp39
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
        }
    
        public string PRODUCT_CD { get; set; }
        public Nullable<System.DateTime> DATE_OFFERED { get; set; }
        public Nullable<System.DateTime> DATE_RETIRED { get; set; }
        public string NAME { get; set; }
        public string PRODUCT_TYPE_CD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
    }
}
